  <footer id="main-footer">
    <div class="container">
      <div class="row">
        <div class="col-md-6">
          <ul class="footer-menu">
            <li>Copyright &copy <?php echo date(Y) ?> Hospital Veterinario Benipeixcar.</li>
          </ul>
          <div class="copyright">
           Diseño y mantenimiento by <a href="http://www.a2informatica.es">A2 Informática.</a>
          </div>
        </div>
       </div>
    </div>
  </footer>
  <script src='<?php echo $config->urls->templates?>assets/js/jquery.js'></script>
<script src='<?php echo $config->urls->templates?>assets/js/bootstrap/button.js'></script>
<script src='<?php echo $config->urls->templates?>assets/js/bootstrap.min.js'></script>
<script src='<?php echo $config->urls->templates?>assets/js/bootstrap/carousel.js'></script>
<script src='<?php echo $config->urls->templates?>assets/js/bootstrap/transition.js'></script>
<script src='<?php echo $config->urls->templates?>assets/js/bootstrap/collapse.js'></script>
<script src='<?php echo $config->urls->templates?>assets/js/bootstrap/modal.js'></script>
<script src='<?php echo $config->urls->templates?>assets/js/bootstrap/dropdown.js'></script>
<script src='<?php echo $config->urls->templates?>assets/js/jquery.visible.min.js'></script>
<script src='<?php echo $config->urls->templates?>assets/js/bootstrap/tab.js'></script>
<script src='<?php echo $config->urls->templates?>assets/js/jquery.isotope.min.js'></script>
<script src='<?php echo $config->urls->templates?>assets/js/jquery.knob.js'></script>
<script src='<?php echo $config->urls->templates?>assets/js/jquery.scrollUp.min.js'></script>
<script src='<?php echo $config->urls->templates?>assets/js/application.js'></script>
<script src='<?php echo $config->urls->templates?>assets/js/modal.js'></script>

</body>

</html>